### PR TITLE
Update dependency org.jetbrains.intellij.plugins:gradle-grammarkit-pl…

### PR DESCRIPTION
**Pull request by hfhbd**
…ugin to v2022

This update needs Java 17

### CODE REVIEW

**Comment by hfhbd** [comment]
Forgot we don't generate Java code, so the JavaCompile attrs are only relevant for fetching the Gradle variant... But we should set the Java Version used by the CI explicitly (current default is Java 11)

**Comment by hfhbd** [comment]
@AlecStrong You don't provide snapshots, do you?

**Comment by AlecStrong** [comment]
nope

**Comment by hfhbd** [comment]
We should really add some tests :D I did publish it locally to test it sql-psi and, surprise, it fails because Gradle GrammarKit input changes in the last releases.

**Comment by hfhbd** [comment]
https://github.com/JetBrains/gradle-grammar-kit-plugin/pull/109

**Comment by AlecStrong** [comment]
yea for sure, one of those things that would be nice but I never have time for

**Comment by hfhbd** [comment]
I copied the conventions of the task inputs to prevent waiting for the PR to be merged.

**Comment by hfhbd** [comment]
I also added a workaround for https://youtrack.jetbrains.com/issue/IDEA-301677 to not the coroutines dependency to each consumer.

**Pull request merged**
