### PR TITLE
Integrate Spotless

### PR DESCRIPTION
**Pull request by veyndan**
Basically the exact same thing as I did in https://github.com/AlecStrong/sql-psi/pull/59.

### CODE REVIEW

**Comment by AlecStrong** [comment]
:+1:

**Comment by AlecStrong** [comment]
we should probably start running github actions on this thing, just a simple `./gradlew build`

**Comment by AlecStrong** [comment]
oh they are set up, just not running on pr?

**Comment by veyndan** [comment]
Yeah seems like it's just set up for `push`. I can create a PR for it now

**Pull request merged**
